name: air_quality_app
description: Air Quality App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: 5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  freezed: 2.4.6
  freezed_annotation: 2.4.1
  get_it: 7.6.6
  json_annotation: 4.8.1
  retrofit: 4.0.3
  shimmer_animation: 2.1.0+1
 
 
  
  
  
  


 

dev_dependencies:
  build_runner: '>=2.3.0 <4.0.0'
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  lint_quido: 1.16.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  

flutter:
  uses-material-design: true