name: air_quality_app
description: Air Quality App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: 5.4.0
  retrofit: 4.0.3
  json_annotation: 4.8.1
  flutter_bloc: 8.1.3
  get_it: 7.6.6
  freezed: 2.4.6
  freezed_annotation: 2.4.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true